### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by lyma** [ryuyax7/bet365_soccer_scraping#1]
Hello!

There is a settings.py file example?

**Comment by ryuya007** [comment]
Hello!

Please refer to the following!
```

url = 'https://www.bet365.com/#/HO/'

# bet365 account
username = ''
password = ''

# LINE
line_token = ''

# chrome
# for mac
profile_dir = '/Users/<your name>/Library/Application\ Support/Google/Chrome'
profile = '<your profile name>'

# slack
slack_url = 'https://hooks.slack.com/services/**************'

# csv file path
csv_file = '<your file path>'

```

**Comment by OEDOARDO** [comment]
Hi, how i can make it work? can you make a full guide?

**Comment by lyma** [comment]
Thanks @ryuyax7 !

Can you put this in the project? :)

Regards,

Lyma

> Hello!
> 
> Please refer to the following!
> 
> ```
> 
> url = 'https://www.bet365.com/#/HO/'
> 
> # bet365 account
> username = ''
> password = ''
> 
> # LINE
> line_token = ''
> 
> # chrome
> # for mac
> profile_dir = '/Users/<your name>/Library/Application\ Support/Google/Chrome'
> profile = '<your profile name>'
> 
> # slack
> slack_url = 'https://hooks.slack.com/services/**************'
> 
> # csv file path
> csv_file = '<your file path>'
> ```
